"""
Leetcode
2026-03-31
3474. Lexicographically Smallest Generated String
Hard

You are given two strings, str1 and str2, of lengths n and m, respectively.

A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:

    If str1[i] == 'T', the of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
    If str1[i] == 'F', the of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.

Return the possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".

 

Example 1:

Input: str1 = "TFTF", str2 = "ab"

Output: "ababa"

Explanation:
The table below represents the string "ababa"
Index	T/F	Substring of length m
0	'T'	"ab"
1	'F'	"ba"
2	'T'	"ab"
3	'F'	"ba"

The strings "ababa" and "ababb" can be generated by str1 and str2.

Return "ababa" since it is the lexicographically smaller string.

Example 2:

Input: str1 = "TFTF", str2 = "abc"

Output: ""

Explanation:

No string that satisfies the conditions can be generated.

Example 3:

Input: str1 = "F", str2 = "d"

Output: "a"

 

Constraints:

    1 <= n == str1.length <= 10^4
    1 <= m == str2.length <= 500
    str1 consists only of 'T' or 'F'.
    str2 consists only of lowercase English characters.


Hint 1
Use dynamic programming.
Hint 2
Fill the fixed part.
Hint 3
Use KMP's next table for DP.
Hint 4
The state is the prefix length and the longest suffix length that matches the pattern.
Hint 5
Each unknown character can be selected from ['a', 'b'].
Hint 6
Can you think of a greedy approach?
"""

from typing import List


class Solution:
    """
    Wrong Answer
    733 / 739 testcases passed
    """

    def generateString(self, str1: str, str2: str) -> str:
        n = len(str1)
        m = len(str2)
        word = [""] * (n + m - 1)

        # fill word with all the str2 in T places
        for i, c1 in enumerate(str1):
            if c1 != "T":
                continue
            for j, c2 in enumerate(str2):
                if not word[i + j]:
                    word[i + j] = c2
                elif word[i + j] != c2:
                    return ""

        str2_l = list(str2)

        def fill(chars: List[str]) -> List[str]:
            if chars == str2_l:
                return []
            idxs = [i for i, c in enumerate(chars) if not c]
            if not idxs:
                return chars
            l = len(idxs)
            for i in range(1 << l):
                for j, idx in enumerate(idxs):
                    mask = 1 << (l - 1 - j)
                    chars[idx] = "b" if i & mask == mask else "a"
                if chars != str2_l:
                    return chars
            return []

        # fill word with chars different from str2 in F places
        for i, c1 in enumerate(str1):
            if c1 != "F":
                continue
            fill_chars = fill(word[i:i+m])
            if not fill_chars:
                return ""
            for j, c2 in enumerate(fill_chars):
                word[i + j] = c2

        # check the ending of word
        if str1[-1] == "F":
            fill_chars = fill(word[n-1:n-1+m])
            if not fill_chars:
                return ""
            for i, c2 in enumerate(fill_chars):
                word[n-1+i] = c2

        return "".join(word)


class Solution1:
    """
    leetcode solution: Greedy
    Runtime 288ms Beats 35.90%
    Memory 19.36MB Beats 82.05%
    """

    def generateString(self, str1: str, str2: str) -> str:
        n, m = len(str1), len(str2)
        s = ["a"] * (n + m - 1)
        fixed = [False] * (n + m - 1)

        # process the case of 'T'
        for i, ch in enumerate(str1):
            if ch == "T":
                for j, c in enumerate(str2, i):
                    if fixed[j] and s[j] != c:
                        return ""
                    s[j], fixed[j] = c, True

        # process the case of 'F'
        for i, ch in enumerate(str1):
            if ch == "F":
                # check if there are already different characters
                if any(str2[j - i] != s[j] for j in range(i, i + m)):
                    continue

                # find the first modifiable position
                for j in range(i + m - 1, i - 1, -1):
                    if not fixed[j]:
                        s[j] = "b"
                        break
                else:
                    return ""

        return "".join(s)
